
basepath = "."

locales = [
  "da",
  "de",
  "en-GB",
  "es",
  "es-ES",
  "fi",
  "fr",
  "it",
  "ja",
  "ko",
  "nb-NO",
  "nl",
  "nn-NO",
  "pl",
  "ru",
  "sv-SE",
  "uk",
  "zh-CN",
  "zh-TW",
]

# Expose the following branches to localization
# Changes to this list should be announced to the l10n team ahead of time.
branches = [
    "main",
]

[env]

[[paths]]
  reference = "app/src/main/res/values/strings.xml"
  l10n = "app/src/main/res/values-{android_locale}/strings.xml"
